document:
  name: Catalogo Nazionale Dati per l'Interoperabilità Semantica

  description: |-
      Catalogo Nazionale Dati per l'Interoperabilità Semantica
  tags:
    - interoperabilità
    - API
    - semantica
    - dati
